name: dekannadarajyotsava_web
description: A Flutter web application for DEKannadaRajyotsava with Google Sheets integration.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  
  # HTTP and API calls
  http: ^1.1.0
  
  # Utilities
  intl: ^0.19.0
  
  # PDF Generation
  pdf: ^3.11.1
  printing: ^5.12.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/